import {
  Home,
  HousePlus,
  User,
  FileText,
  MessageSquare,
  Settings,
  Bell,
  ChevronLeft,
  ChevronRight,
  ArrowRight,
  ArrowLeft,
  ArrowUpRight,
  ArrowLeftRight,
  CornerDownRight,
  RefreshCw,
  TrendingDown,
  Plus,
  Check,
  Trash2,
  LogOut,
  Hash,
  Search,
  Upload,
  Flag,
  Edit,
  Shield,
  DollarSign,
  TrendingUp,
  X,
  Link,
  AlertTriangle,
  MoreHorizontal,
  Menu,
  Calendar,
  ChevronDown,
  Info,
  Cloud,
  Calculator,
  Mail,
  Briefcase,
  Code,
  Palette,
  Landmark,
  Users,
  Newspaper,
  Star,
  ListFilter,
  Eye,
  EyeOff,
  Image as ImageIcon,
  Zap,
  ShoppingCart,
  Car,
  Ticket,
  HeartPulse,
  ShieldCheck,
  Repeat,
  Wifi,
  Smartphone,
  Tag,
} from "lucide-react";

export const ICON_MAP = {
  home: Home,
  about: User,
  expenses: FileText,
  // Distinct from `home` (the / landing) — the + decorator reads as "your
  // shared household" rather than a generic dwelling, and keeps Home/House
  // visually separable in the bottom mobile nav.
  household: HousePlus,
  forum: MessageSquare,
  settings: Settings,
  bell: Bell,
  chevLeft: ChevronLeft,
  chevRight: ChevronRight,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUpRight: ArrowUpRight,
  swap: ArrowLeftRight,
  cornerDownRight: CornerDownRight,
  refresh: RefreshCw,
  trendDown: TrendingDown,
  plus: Plus,
  check: Check,
  trash: Trash2,
  logout: LogOut,
  hash: Hash,
  search: Search,
  upload: Upload,
  flag: Flag,
  edit: Edit,
  shield: Shield,
  dollar: DollarSign,
  trendUp: TrendingUp,
  x: X,
  link: Link,
  alert: AlertTriangle,
  more: MoreHorizontal,
  menu: Menu,
  calendar: Calendar,
  chevDown: ChevronDown,
  info: Info,
  weather: Cloud,
  math: Calculator,
  mail: Mail,
  linkedin: Briefcase,
  github: Code,
  palette: Palette,
  bank: Landmark,
  community: Users,
  feed: Newspaper,
  star: Star,
  filter: ListFilter,
  eye: Eye,
  eyeOff: EyeOff,
  image: ImageIcon,
  // Expense-category glyphs
  rent: Home,
  utilities: Zap,
  groceries: ShoppingCart,
  transportation: Car,
  entertainment: Ticket,
  healthcare: HeartPulse,
  insurance: ShieldCheck,
  subscriptions: Repeat,
  internet: Wifi,
  phone: Smartphone,
  tag: Tag,
} as const;

export type IconName = keyof typeof ICON_MAP;

export function Icon({
  name,
  size = 16,
  className,
  strokeWidth = 1.5,
}: {
  name: IconName;
  size?: number;
  className?: string;
  strokeWidth?: number;
}) {
  const Comp = ICON_MAP[name];
  if (!Comp) return null;
  return <Comp size={size} strokeWidth={strokeWidth} className={className} />;
}
